import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex fixed top-0 left-0 justify-around w-full">
          <div>
            <h1 className="text-center text-xl">ZAISAN</h1>
            <p>Collective Wealth Creation</p>
          </div>
          <ul className="flex ">
          <li className="mx-4"><Link href="/#">Funding</Link></li>
          <li className="mx-4"><Link href="/investors">Investors</Link></li>
          <li className="mx-4"><Link href="/company">company</Link></li>
          <li className="mx-4"><Link href="/about-us">about us</Link></li>
          <li className="mx-4"><Link href="/#">FAQ</Link></li>
          <li className="mx-4"><Link href="/#">Portfolio</Link></li>

          </ul>
        </nav>
        {children}</body>
      <footer className=" bg-white pt-[10em] text-center text-3xl">Impressum</footer>
    </html>
  );
}
